### ISSUE TITLE
Refactor-Checklist

### ISSUE THREAD

**Issue by slumpsand** [slumpsand/interpreter#3]
- [x] rename `scope_init()` and `scope_term()` to `stack_init()` and `stack_term()`
- [x] rename `scope.h` and `scope.c` into something like `environment`
- [x] move all the scope stuff into a folder named `env` or something like that
- [x] sort `env.c` according to `env.h`
- [x] implement float variable-types
  - [x] implement `var* declare_float(const char* name, float value)`
  - [x] run tests on it
- [x] refactor `print_sc(scope* sc)` to `print_st()` and just print the stack
