### ISSUE TITLE
Feature Checklist #1

### ISSUE THREAD

**Issue by slumpsand** [slumpsand/interpreter#6]
- [ ] implement a constructor for each node
  - __Block Nodes__
    - [ ] `block* fs(const char* itname, int count, block* b)` (simple for-loop)
    - [ ] `block* fc(expr* init, expr* cond, expr* each, block* b)` (complex for-loop)
    - [ ] `block* wl(expr* cond, block* b)` (while loop)
    - [ ] `block* st(call* c)` (statment / call alias)
  - __Expr Nodes__
    - [ ] `expr* cl(char* name, expr* args)` (call-expr)
    - [ ] `expr* as(char* name, expr* val` (assign-expr)
    - [ ] `expr* dc(char* name, char* type, expr* val)` (declaration-expr)
    - [ ] `expr* ic(char* name, int isInc)` (increment / decrement - expr)
